# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AppleContacts < Formula
  desc "CLI for searching and querying Apple Contacts via AppleScript"
  homepage "https://github.com/fishfisher/apple-contacts"
  version "0.1.1"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/fishfisher/apple-contacts/releases/download/v0.1.1/apple-contacts_0.1.1_darwin_amd64.tar.gz"
    sha256 "9dda2e4c4b93f824c77c7285c90f3481965eec464e51ea369e5ffcde0c5872d4"

    def install
      bin.install "apple-contacts"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/fishfisher/apple-contacts/releases/download/v0.1.1/apple-contacts_0.1.1_darwin_arm64.tar.gz"
    sha256 "344adc7aa6c2e18d5ff1d91382ed3bba1768b94e35933462756f66bb62ccbfdf"

    def install
      bin.install "apple-contacts"
    end
  end

  test do
    system "#{bin}/apple-contacts", "--help"
  end
end
