# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private_strategy"
class AppleNotes < Formula
  desc "CLI for Apple Notes with SQLite for fast reads and AppleScript for writes"
  homepage "https://github.com/fishfisher/apple-notes"
  version "0.5.2"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/fishfisher/apple-notes/releases/download/v0.5.2/apple-notes_0.5.2_darwin_amd64.tar.gz", using: FishfisherPrivateReleaseDownloadStrategy
    sha256 "b0965767a4196955e279c84e2f04b15abdac5bb41127356364258a87bfa1fcce"

    def install
      bin.install "apple-notes"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/fishfisher/apple-notes/releases/download/v0.5.2/apple-notes_0.5.2_darwin_arm64.tar.gz", using: FishfisherPrivateReleaseDownloadStrategy
    sha256 "2c965e70b2bf690b1890178e9514c46d2d7ee3db990e8c73cadd5ef5fc2e8265"

    def install
      bin.install "apple-notes"
    end
  end

  test do
    system "#{bin}/apple-notes", "version"
  end
end
