# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AppleNotes < Formula
  desc "CLI for Apple Notes with SQLite for fast reads and AppleScript for writes"
  homepage "https://github.com/fishfisher/apple-notes"
  version "0.2.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/fishfisher/apple-notes/releases/download/v0.2.0/apple-notes_0.2.0_darwin_amd64.tar.gz"
    sha256 "d6123df5c7805a6a470ff829d4344f5e9b1953849cc93efd53a301f75d938602"

    def install
      bin.install "apple-notes"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/fishfisher/apple-notes/releases/download/v0.2.0/apple-notes_0.2.0_darwin_arm64.tar.gz"
    sha256 "26b27233ad70bd6c8040a6069be8ae28ca423eac63377e73c3d3392cd8c8bf2d"

    def install
      bin.install "apple-notes"
    end
  end

  test do
    system "#{bin}/apple-notes", "version"
  end
end
