# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AppleContacts < Formula
  desc "CLI for searching and querying Apple Contacts via AppleScript"
  homepage "https://github.com/fishfisher/apple-contacts"
  version "0.1.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/fishfisher/apple-contacts/releases/download/v0.1.0/apple-contacts_0.1.0_darwin_amd64.tar.gz"
    sha256 "272ca317a1fc7fcebb84d26f38804de5412be4abfc6fcb57cb224e7cd5babfc6"

    def install
      bin.install "apple-contacts"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/fishfisher/apple-contacts/releases/download/v0.1.0/apple-contacts_0.1.0_darwin_arm64.tar.gz"
    sha256 "26a8b0e2c7e4db249f520384f65ee7e7f005738fed65046c8b9167d9dca1236a"

    def install
      bin.install "apple-contacts"
    end
  end

  test do
    system "#{bin}/apple-contacts", "--help"
  end
end
