# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AppleNotes < Formula
  desc "CLI for Apple Notes with SQLite for fast reads and AppleScript for writes"
  homepage "https://github.com/fishfisher/apple-notes"
  version "0.5.1"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/fishfisher/apple-notes/releases/download/v0.5.1/apple-notes_0.5.1_darwin_amd64.tar.gz"
    sha256 "c8b526dfda124c403eeb9a003ebf26136dfe2bdef6de15282ed88e0cbc1ef18b"

    def install
      bin.install "apple-notes"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/fishfisher/apple-notes/releases/download/v0.5.1/apple-notes_0.5.1_darwin_arm64.tar.gz"
    sha256 "668d3d64bb0ca3dff9a41ae36b111b21c6bbcbe17142cdabe97a11e3a230bfa8"

    def install
      bin.install "apple-notes"
    end
  end

  test do
    system "#{bin}/apple-notes", "version"
  end
end
