# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private_strategy"
class NorskTippingCli < Formula
  desc "CLI for buying lottery tickets from Norsk Tipping"
  homepage "https://github.com/fishfisher/norsk-tipping-cli"
  version "1.0.8"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/fishfisher/norsk-tipping-cli/releases/download/v1.0.8/norsk-tipping-cli-darwin-amd64", using: FishfisherPrivateReleaseDownloadStrategy
    sha256 "b1244e67dd7d19b7b35d06e20eb2a6fdb789424b4373f8e60c47d989fb0a92c2"

    def install
      bin.install Dir["norsk-tipping*"].first => "norsk-tipping"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/fishfisher/norsk-tipping-cli/releases/download/v1.0.8/norsk-tipping-cli-darwin-arm64", using: FishfisherPrivateReleaseDownloadStrategy
    sha256 "11a2ac479b69eb904a90c1789daf6ebf6f62b104891c3337fb5319341f59f4c7"

    def install
      bin.install Dir["norsk-tipping*"].first => "norsk-tipping"
    end
  end

  test do
    assert_match "Norsk Tipping", shell_output("#{bin}/norsk-tipping --help")
  end
end
