# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private_strategy"
class NorskTipping < Formula
  desc "CLI for buying lottery tickets from Norsk Tipping"
  homepage "https://github.com/fishfisher/norsk-tipping-cli"
  version "1.0.9"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/fishfisher/norsk-tipping-cli/releases/download/v1.0.9/norsk-tipping-cli-darwin-amd64", using: FishfisherPrivateReleaseDownloadStrategy
    sha256 "57e1ff4a5c2d2c6efcccd4a224d73e3bddd4f950bef8c4d584a351b7216befdb"

    def install
      bin.install Dir["norsk-tipping*"].first => "norsk-tipping"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/fishfisher/norsk-tipping-cli/releases/download/v1.0.9/norsk-tipping-cli-darwin-arm64", using: FishfisherPrivateReleaseDownloadStrategy
    sha256 "2117eb781b9a6a69d765756ece0ea2f6c16a60af042a3eae1fc17b61760b7fc4"

    def install
      bin.install Dir["norsk-tipping*"].first => "norsk-tipping"
    end
  end

  test do
    assert_match "Norsk Tipping", shell_output("#{bin}/norsk-tipping --help")
  end
end
