# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private_strategy"
class OdaCli < Formula
  desc "CLI for ordering groceries from Oda.com"
  homepage "https://github.com/fishfisher/oda-cli"
  version "1.1.2"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/fishfisher/oda-cli/releases/download/v1.1.2/oda-cli-darwin-amd64", using: FishfisherPrivateReleaseDownloadStrategy
    sha256 "f992598c6ce91ba9b014d1d5596d6ffc51a7f0a5e607ed01561079fa96227d61"

    def install
      bin.install Dir["oda*"].first => "oda"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/fishfisher/oda-cli/releases/download/v1.1.2/oda-cli-darwin-arm64", using: FishfisherPrivateReleaseDownloadStrategy
    sha256 "7d7dcda6af0930342de59c43084dda1485e153f348bce0849ed258a8980feed6"

    def install
      bin.install Dir["oda*"].first => "oda"
    end
  end

  test do
    assert_match "Oda", shell_output("#{bin}/oda --help")
  end
end
