# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private_strategy"
class Sonoscli < Formula
  desc "Control Sonos speakers from the command line"
  homepage "https://github.com/fishfisher/sonoscli"
  version "0.2.1"
  license "MIT"

  depends_on "macos"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fishfisher/sonoscli/releases/download/v0.2.1/sonoscli_0.2.1_darwin_amd64.zip", using: FishfisherPrivateReleaseDownloadStrategy
      sha256 "c734bbd003e5edbfffe5574d63c3c7e9c3b5d704f18a09a9ca841e7904e2d01b"

      def install
        bin.install "sonos"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fishfisher/sonoscli/releases/download/v0.2.1/sonoscli_0.2.1_darwin_arm64.zip", using: FishfisherPrivateReleaseDownloadStrategy
      sha256 "00def2204c1d89cb0b18d80c277cbf666def9ce2c5b7d8a32a0d54c3d582d140"

      def install
        bin.install "sonos"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fishfisher/sonoscli/releases/download/v0.2.1/sonoscli_0.2.1_linux_amd64.tar.gz", using: FishfisherPrivateReleaseDownloadStrategy
      sha256 "1cb66256bc383b6ea1c86dfebc1b7386f7a8e5a489314cbab3090f39306e41e4"
      def install
        bin.install "sonos"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fishfisher/sonoscli/releases/download/v0.2.1/sonoscli_0.2.1_linux_arm64.tar.gz", using: FishfisherPrivateReleaseDownloadStrategy
      sha256 "b463daee6f2af98e7aa5f6ff1ba6d2229e6dba1efa52f4647065803245225fa5"
      def install
        bin.install "sonos"
      end
    end
  end

  test do
    assert_match "Control Sonos speakers", shell_output("#{bin}/sonos --help")
  end
end
