# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private_strategy"
class Sonoscli < Formula
  desc "Control Sonos speakers from the command line"
  homepage "https://github.com/fishfisher/sonoscli"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fishfisher/sonoscli/releases/download/v0.2.2/sonoscli_0.2.2_darwin_amd64.zip", using: FishfisherPrivateReleaseDownloadStrategy
      sha256 "430048912484c5e3542685912344e9ef527ae80466a8ceb9ee498453e494b47e"

      def install
        bin.install "sonos"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fishfisher/sonoscli/releases/download/v0.2.2/sonoscli_0.2.2_darwin_arm64.zip", using: FishfisherPrivateReleaseDownloadStrategy
      sha256 "8d0e92be5c0b580b83d46726b20a79dd136c84cea130de5bea77f412d7d0255b"

      def install
        bin.install "sonos"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fishfisher/sonoscli/releases/download/v0.2.2/sonoscli_0.2.2_linux_amd64.tar.gz", using: FishfisherPrivateReleaseDownloadStrategy
      sha256 "9515fd4c32f0c077a1b49a69b79bde4e074645898dc7c83d55ee3f629b25c410"
      def install
        bin.install "sonos"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fishfisher/sonoscli/releases/download/v0.2.2/sonoscli_0.2.2_linux_arm64.tar.gz", using: FishfisherPrivateReleaseDownloadStrategy
      sha256 "488247a5085b750f5e2217bbbfab7f1e6169e0ffa5ff9b19a6ec883327523fc3"
      def install
        bin.install "sonos"
      end
    end
  end

  test do
    assert_match "Control Sonos speakers", shell_output("#{bin}/sonos --help")
  end
end
